@startuml Pow

class Pow 
class Juego
class JuegoPelota
class Pelota 
class Comida 
class Recompensa
class Moneda 
class Energia
class Maximo
class Medio 
class Bajo
class Hambre
Class Nivel 
Class Pow {
    -color 
    -tamano
    -porcentaje_Salud
+ Duchar
+Comer 
+Cagar
}
Pow --o Juego
Juego <-- JuegoPelota
Pelota --* JuegoPelota

Pow --o Energia
Energia --> Nivel
Nivel o--> Maximo 
Nivel o--> Medio 
Nivel o--> Bajo

Pow --o Recompensa
Recompensa --> Moneda

Pow --* Hambre

@enduml
